"""In-process OpenAI-compatible vLLM test double.

Used only by the HTTP integration suite. It speaks vLLM's wire format so tests can
exercise deterministic streaming, usage, and failure behavior without a GPU.

**Fault injection** (to exercise the degraded paths mock-first is meant to buy) —
set via ``X-Mock-Fault`` header or ``?fault=`` query param:

- ``error_503``  → respond 503 immediately (simulates a preempted/unavailable node).
- ``slow_ttft``  → long delay before the first token (simulates queueing / slow TTFT).
- ``mid_abort``  → stream a few deltas then drop the connection without a final chunk
                   or ``[DONE]`` (simulates mid-stream preemption).
- ``no_usage``   → omit the trailing usage chunk (forces the backend's token fallback).

Latency between tokens is tunable via ``X-Mock-Latency`` / ``?latency=`` (seconds).
"""

from __future__ import annotations

import asyncio
import json
import time
from collections.abc import AsyncGenerator

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse, StreamingResponse

app = FastAPI(title="Mock vLLM", version="0.1.0")

MODEL_ID = "gemma-mock"
SLOW_TTFT_S = 3.0
MOCK_REASONING = "The user wants a concise deterministic test response."
MOCK_TOOL_CALL_ID = "call_mock_weather"
MOCK_TOOL_ARGUMENTS = '{"city":"Tashkent"}'


def _reply_text(messages: list[dict]) -> str:
    """Deterministic canned reply that echoes the last user message."""
    last_user = ""
    for m in reversed(messages):
        if m.get("role") == "user":
            content = m.get("content", "")
            if isinstance(content, list):  # OpenAI content-parts form
                content = " ".join(
                    p.get("text", "")
                    for p in content
                    if isinstance(p, dict) and p.get("type") == "text"
                )
            last_user = str(content)
            break
    snippet = (last_user[:120] + "…") if len(last_user) > 120 else last_user
    return (
        "Hello! This is a mock streaming response from the local development vLLM. "
        f"You said: “{snippet}”. "
        "Everything here is generated by app/mock_services/vllm.py — swap MODELS_CONFIG "
        "to a real endpoint to use a real model."
    )


def _tool_result_reply(messages: list[dict]) -> str | None:
    if messages and messages[-1].get("role") == "tool":
        return f"The tool returned: {messages[-1].get('content', '')}"
    return None


def _last_user_text(messages: list[dict]) -> str:
    for m in reversed(messages):
        if m.get("role") == "user":
            content = m.get("content", "")
            if isinstance(content, list):
                content = " ".join(
                    p.get("text", "")
                    for p in content
                    if isinstance(p, dict) and p.get("type") == "text"
                )
            return str(content)
    return ""


def _mock_title(messages: list[dict]) -> str:
    """A short, plausible title from the first message — so auto-titling is visibly
    exercised in dev (a real model would write a nicer one)."""
    words = [w for w in _last_user_text(messages).split() if w][:6]
    title = " ".join(w[:1].upper() + w[1:] for w in words)
    return title or "New Chat"


def _est_prompt_tokens(messages: list[dict]) -> int:
    chars = 0
    for m in messages:
        c = m.get("content", "")
        if isinstance(c, list):
            c = " ".join(p.get("text", "") for p in c if isinstance(p, dict))
        chars += len(str(c))
    return max(1, chars // 4)


def _usage_payload(
    messages: list[dict], completion_tokens: int, reasoning_tokens: int = 0
) -> dict:
    prompt_tokens = _est_prompt_tokens(messages)
    cached_tokens = 1 if "cached" in _last_user_text(messages).lower() else 0
    return {
        "prompt_tokens": prompt_tokens,
        "completion_tokens": completion_tokens,
        "total_tokens": prompt_tokens + completion_tokens,
        "prompt_tokens_details": {"cached_tokens": min(cached_tokens, prompt_tokens)},
        "completion_tokens_details": {"reasoning_tokens": reasoning_tokens},
    }


def _chunk(
    model: str,
    created: int,
    *,
    delta: dict | None = None,
    finish_reason: str | None = None,
    usage: dict | None = None,
) -> str:
    choices = []
    if delta is not None or finish_reason is not None:
        choices = [{"index": 0, "delta": delta or {}, "finish_reason": finish_reason}]
    payload: dict = {
        "id": "chatcmpl-mock",
        "object": "chat.completion.chunk",
        "created": created,
        "model": model,
        "choices": choices,
    }
    if usage is not None:
        payload["usage"] = usage
    return f"data: {json.dumps(payload)}\n\n"


def _resolve_fault(request: Request, body: dict) -> tuple[str | None, float]:
    fault = request.headers.get("x-mock-fault") or request.query_params.get("fault")
    latency_raw = request.headers.get("x-mock-latency") or request.query_params.get("latency")
    try:
        latency = float(latency_raw) if latency_raw else 0.03
    except ValueError:
        latency = 0.03
    return (fault or None), latency


@app.get("/v1/models")
async def list_models() -> dict:
    return {
        "object": "list",
        "data": [{"id": MODEL_ID, "object": "model", "created": 0, "owned_by": "coreai-mock"}],
    }


@app.get("/health")
async def health() -> dict:
    return {"status": "ok"}


@app.post("/v1/chat/completions")
async def chat_completions(request: Request):
    body = await request.json()
    messages = body.get("messages", [])
    model = body.get("model", MODEL_ID)
    stream = bool(body.get("stream", False))
    include_usage = bool((body.get("stream_options") or {}).get("include_usage", True))

    fault, latency = _resolve_fault(request, body)

    if fault == "error_503":
        return JSONResponse(
            {
                "error": {
                    "message": "mock: upstream unavailable",
                    "type": "server_error",
                    "code": 503,
                }
            },
            status_code=503,
        )

    # Short max_tokens is the auto-title request shape — echo a concise title instead of
    # the canned chat reply, so the titling path is testable against the mock.
    max_tokens = body.get("max_tokens")
    is_title = isinstance(max_tokens, int) and max_tokens <= 32
    tools = body.get("tools") or []
    tool_choice = body.get("tool_choice", "auto")
    should_call_tool = bool(tools) and tool_choice != "none" and not _tool_result_reply(messages)
    selected_tool = None
    if should_call_tool:
        if isinstance(tool_choice, dict):
            selected_name = (tool_choice.get("function") or {}).get("name")
            selected_tool = next(
                (tool for tool in tools if (tool.get("function") or {}).get("name") == selected_name),
                None,
            )
        selected_tool = selected_tool or tools[0]

    reply = (
        _mock_title(messages)
        if is_title
        else (_tool_result_reply(messages) or _reply_text(messages))
    )
    words = reply.split(" ")
    thinking = bool((body.get("chat_template_kwargs") or {}).get("enable_thinking", False))
    reasoning_words = MOCK_REASONING.split(" ") if thinking and not is_title else []
    completion_tokens = (
        len(reasoning_words) + max(1, len(MOCK_TOOL_ARGUMENTS) // 4)
        if should_call_tool
        else len(words) + len(reasoning_words)
    )
    usage = _usage_payload(messages, completion_tokens, len(reasoning_words))
    created = int(time.time())

    if not stream:
        if should_call_tool:
            tool_name = selected_tool["function"]["name"]
            return JSONResponse(
                {
                    "id": "chatcmpl-mock",
                    "object": "chat.completion",
                    "created": created,
                    "model": model,
                    "choices": [
                        {
                            "index": 0,
                            "message": {
                                "role": "assistant",
                                "content": None,
                                **(
                                    {"reasoning_content": MOCK_REASONING}
                                    if reasoning_words
                                    else {}
                                ),
                                "tool_calls": [
                                    {
                                        "id": MOCK_TOOL_CALL_ID,
                                        "type": "function",
                                        "function": {
                                            "name": tool_name,
                                            "arguments": MOCK_TOOL_ARGUMENTS,
                                        },
                                    }
                                ],
                            },
                            "finish_reason": "tool_calls",
                        }
                    ],
                    "usage": usage,
                    "system_fingerprint": "mock-vllm-fingerprint",
                }
            )
        return JSONResponse(
            {
                "id": "chatcmpl-mock",
                "object": "chat.completion",
                "created": created,
                "model": model,
                "choices": [
                    {
                        "index": 0,
                        "message": {
                            "role": "assistant",
                            "content": reply,
                            **(
                                {"reasoning_content": MOCK_REASONING}
                                if reasoning_words
                                else {}
                            ),
                        },
                        "finish_reason": "stop",
                    }
                ],
                "usage": usage,
                "system_fingerprint": "mock-vllm-fingerprint",
            }
        )

    async def gen() -> AsyncGenerator[str, None]:
        if fault == "slow_ttft":
            await asyncio.sleep(SLOW_TTFT_S)

        # First chunk carries the assistant role.
        yield _chunk(model, created, delta={"role": "assistant", "content": ""})

        for i, word in enumerate(reasoning_words):
            piece = word if i == 0 else " " + word
            yield _chunk(model, created, delta={"reasoning_content": piece})
            await asyncio.sleep(latency)

        if should_call_tool:
            tool_name = selected_tool["function"]["name"]
            yield _chunk(
                model,
                created,
                delta={
                    "tool_calls": [
                        {
                            "index": 0,
                            "id": MOCK_TOOL_CALL_ID,
                            "type": "function",
                            "function": {"name": tool_name, "arguments": ""},
                        }
                    ]
                },
            )
            yield _chunk(
                model,
                created,
                delta={
                    "tool_calls": [
                        {"index": 0, "function": {"arguments": '{"city":'}}
                    ]
                },
            )
            yield _chunk(
                model,
                created,
                delta={
                    "tool_calls": [
                        {"index": 0, "function": {"arguments": '"Tashkent"}'}}
                    ]
                },
            )
            yield _chunk(model, created, delta={}, finish_reason="tool_calls")
            if include_usage and fault != "no_usage":
                yield _chunk(model, created, usage=usage)
            yield "data: [DONE]\n\n"
            return

        for i, word in enumerate(words):
            piece = word if i == 0 else " " + word
            yield _chunk(model, created, delta={"content": piece})
            await asyncio.sleep(latency)

            # Simulate a dropped upstream partway through: stop without a finish chunk.
            if fault == "mid_abort" and i >= 4:
                return

        # Terminal chunk with finish_reason.
        yield _chunk(model, created, delta={}, finish_reason="stop")

        # Trailing usage chunk (empty choices), as vLLM does with include_usage.
        if include_usage and fault != "no_usage":
            yield _chunk(
                model,
                created,
                usage=usage,
            )

        yield "data: [DONE]\n\n"

    return StreamingResponse(gen(), media_type="text/event-stream")
