"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-05

Hand-authored (not autogenerated): autogenerate does not emit extensions, native
enum types, or the updated_at trigger. Constraint/index names follow the metadata
naming convention so later autogenerate diffs stay stable.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Native enum types. create_type=False → we create/drop them explicitly below.
message_role = postgresql.ENUM(
    "user", "assistant", "system", name="message_role", create_type=False
)
finish_reason = postgresql.ENUM(
    "stop", "stopped", "length", name="finish_reason", create_type=False
)
ocr_status = postgresql.ENUM(
    "queued", "processing", "done", "failed", "expired", name="ocr_status", create_type=False
)
usage_type = postgresql.ENUM("chat", "ocr", name="usage_type", create_type=False)

UPDATED_AT_FN = """
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


def upgrade() -> None:
    bind = op.get_bind()

    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    for enum in (message_role, finish_reason, ocr_status, usage_type):
        enum.create(bind, checkfirst=True)

    # --- users ---
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("locale", sa.String(5), server_default="uz", nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )

    # --- conversations ---
    op.create_table(
        "conversations",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(200), nullable=True),
        sa.Column("model", sa.String(128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_conversations"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],
                                name="fk_conversations_user_id_users", ondelete="CASCADE"),
    )
    op.create_index("ix_conversations_user_id_updated_at", "conversations",
                    ["user_id", "updated_at"])

    # --- messages ---
    op.create_table(
        "messages",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("conversation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role", message_role, nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("model", sa.String(128), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("finish_reason", finish_reason, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_messages"),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"],
                                name="fk_messages_conversation_id_conversations", ondelete="CASCADE"),
    )
    op.create_index("ix_messages_conversation_id_created_at", "messages",
                    ["conversation_id", "created_at"])

    # --- ocr_jobs (dormant) ---
    op.create_table(
        "ocr_jobs",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("session_id", sa.String(64), nullable=True),
        sa.Column("filename", sa.String(512), nullable=False),
        sa.Column("status", ocr_status, server_default=sa.text("'queued'"), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("result_text", sa.Text(), nullable=True),
        sa.Column("result_json", postgresql.JSONB(), nullable=True),
        sa.Column("storage_key", sa.String(512), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_ocr_jobs"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],
                                name="fk_ocr_jobs_user_id_users", ondelete="SET NULL"),
        sa.CheckConstraint("user_id IS NOT NULL OR session_id IS NOT NULL",
                           name="owner_present"),
    )
    op.create_index("ix_ocr_jobs_user_id", "ocr_jobs", ["user_id"])
    op.create_index("ix_ocr_jobs_session_id", "ocr_jobs", ["session_id"])
    op.create_index("ix_ocr_jobs_status", "ocr_jobs", ["status"])
    op.create_index("ix_ocr_jobs_expires_at", "ocr_jobs", ["expires_at"])

    # --- usage_events ---
    op.create_table(
        "usage_events",
        sa.Column("id", postgresql.UUID(as_uuid=True),
                  server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("session_id", sa.String(64), nullable=True),
        sa.Column("type", usage_type, nullable=False),
        sa.Column("model", sa.String(128), nullable=True),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("pages", sa.Integer(), server_default="0", nullable=False),
        sa.Column("message_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("ocr_job_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_usage_events"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],
                                name="fk_usage_events_user_id_users", ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"],
                                name="fk_usage_events_message_id_messages", ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["ocr_job_id"], ["ocr_jobs.id"],
                                name="fk_usage_events_ocr_job_id_ocr_jobs", ondelete="SET NULL"),
        sa.CheckConstraint("user_id IS NOT NULL OR session_id IS NOT NULL",
                           name="owner_present"),
    )
    op.create_index("ix_usage_events_user_id_created_at", "usage_events",
                    ["user_id", "created_at"])
    op.create_index("ix_usage_events_session_id_created_at", "usage_events",
                    ["session_id", "created_at"])

    # --- updated_at trigger (only the mutable table) ---
    op.execute(UPDATED_AT_FN)
    op.execute(
        "CREATE TRIGGER trg_conversations_updated_at BEFORE UPDATE ON conversations "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
    )


def downgrade() -> None:
    bind = op.get_bind()

    op.execute("DROP TRIGGER IF EXISTS trg_conversations_updated_at ON conversations")

    op.drop_table("usage_events")
    op.drop_table("ocr_jobs")
    op.drop_table("messages")
    op.drop_table("conversations")
    op.drop_table("users")

    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")

    for enum in (usage_type, ocr_status, finish_reason, message_role):
        enum.drop(bind, checkfirst=True)

    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
    op.execute("DROP EXTENSION IF EXISTS citext")
